---
version: '3.1'
services:
  jenkins:
    build:
      args:
        gid: '${GROUP_ID}'
        uid: '${USER__ID}'
      context: './jenkins'
    container_name: 'jenkins'
    environment:
      CASC_JENKINS_CONFIG: '/usr/share/jenkins/ref/casc_configs'
      JAVA_OPTS: '-Djenkins.install.runSetupWizard=false'
      JENKINS_OPTS: '--prefix=/jenkins'
    image: 'eliezerchavez/jenkins'
    networks:
      - 'tools'
    ports:
      # - 8080:8080
      - 50000:50000
    volumes:
      - './storage/jenkins/home:/var/jenkins_home'
      - './jenkins/conf/jenkins.yml:/usr/share/jenkins/ref/casc_configs/jenkins.yml'
      - '/var/run/docker.sock:/var/run/docker.sock'
  nexus:
    container_name: nexus
    environment:
      NEXUS_CONTEXT: 'nexus'
    image: sonatype/nexus3:latest
    networks:
      - 'tools'
    # ports:
    #   - 8081:8081
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    volumes:
      - './storage/nexus/data:/nexus-data'
  nginx:
    container_name: nginx
    depends_on:
      - jenkins
      - nexus
      - sonarqube
    image: nginx:stable
    networks:
      - 'tools'
    ports:
      - 80:80
      - 443:443
    volumes:
      - './storage/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf'
  postgres:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    image: postgres:13
    networks:
      - 'tools'
    # ports:
    #   - 5432:5432
    volumes:
      - './storage/postgres/conf/postgres-initdb.sql:/docker-entrypoint-initdb.d/init.sql'
      - './storage/postgres/data:/var/lib/postgresql/data'
  sonarqube:
    container_name: sonarqube
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_USERNAME: 'sonar'
      SONAR_JDBC_PASSWORD: 'sonar'
      SONAR_JDBC_URL: 'jdbc:postgresql://postgres/sonar'
      SONAR_WEB_CONTEXT: '/sonarqube'
    image: sonarqube:8-community
    networks:
      - 'tools'
    # ports:
    #   - 9000:9000
    volumes:
      - './storage/sonarqube/data:/opt/sonarqube/data'
      - './storage/sonarqube/logs:/opt/sonarqube/logs'
      - './storage/sonarqube/extensions:/opt/sonarqube/extensions'
networks:
  tools: