---
- become: true
  connection: local
  hosts: localhost
  tasks:
    - import_tasks: ansible/01_prereq.yml
    - import_tasks: ansible/02_docker.yml
    - import_tasks: ansible/03_postgres.yml
    - import_tasks: ansible/04_sonarqube.yml
    - import_tasks: ansible/05_nexus.yml
    - import_tasks: ansible/06_jenkins.yml
    - import_tasks: ansible/07_nginx.yml
  vars:
    home: '/home/{{ username }}/cicd-toolchain'
    server: 'toolchain.eastus.cloudapp.azure.com'
    storage: '{{ home }}/storage'
    username: 'tools'
  