---
- name: "[Jenkins] create volume paths"
  file:
    group: "{{ username }}"
    owner: "{{ username }}"
    path: "{{ storage }}/{{ item }}"
    state: directory
  loop:
    - "jenkins/home"
    - "jenkins/conf"

- name: "[Jenkins] calculating buildargs for docker image (gid)"
  shell: "id -g {{ username }}"
  register: GROUP_ID
- name: "[Jenkins] calculating buildargs for docker image (uid)"
  shell: "id -u {{ username }}"
  register: USER__ID

- name: "[Jenkins] copy configuration files"
  copy:
    dest: "{{ storage }}/jenkins/conf"
    group: "{{ username }}"
    mode: 0644
    owner: "{{ username }}"
    src: "jenkins/"

- name: "[Jenkins] build docker image"
  docker_image:
    build:
      args:
        gid: "{{ GROUP_ID.stdout }}"
        uid: "{{ USER__ID.stdout }}"
      path: "{{ storage }}/jenkins/conf"
      pull: false
    name: "toolchain/jenkins"
    source: build

- name: "[Jenkins] remove unnecesary files"
  file:
    path: "{{ storage }}/jenkins/conf"
    state: "{{ item }}"
  loop:
    - absent
    - directory

- name: "[Jenkins] generating configuration files"
  template:
    dest: "{{ storage }}/jenkins/conf/config.yml"
    group: "{{ username }}"
    owner: "{{ username }}"
    src: "ansible/templates/jenkins/config.j2"

- name: "[Jenkins] start container"
  docker_container:
    env:
      CASC_JENKINS_CONFIG: "/usr/share/jenkins/ref/casc_configs"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      JENKINS_OPTS: "--prefix=/jenkins"
    image: toolchain/jenkins
    name: jenkins
    networks:
      - name: tools
    restart_policy: unless-stopped
    state: started
    volumes:
      - "{{ storage }}/jenkins/home:/var/jenkins_home"
      - "{{ storage }}/jenkins/conf/config.yml:/usr/share/jenkins/ref/casc_configs/config.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"

- name: "[Jenkins] associate jenkins to docker group"
  shell: |-
    docker exec -u root jenkins bash -c "getent group docker || groupadd -rg $(getent group docker | cut -d':' -f3) docker && usermod -aG docker jenkins"

- name: "[Jenkins] restart container"
  docker_container:
    env:
      CASC_JENKINS_CONFIG: "/usr/share/jenkins/ref/casc_configs"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      JENKINS_OPTS: "--prefix=/jenkins"
    image: toolchain/jenkins
    name: jenkins
    networks:
      - name: tools
    restart: true
    restart_policy: unless-stopped
    state: started
    volumes:
      - "{{ storage }}/jenkins/home:/var/jenkins_home"
      - "{{ storage }}/jenkins/conf/config.yml:/usr/share/jenkins/ref/casc_configs/config.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
