- name: "[NGINX] start container"
  docker_container:
    image: nginx:stable
    name: nginx
    networks:
      - name: tools
    ports:
      - 80:80
      - 443:443
    restart_policy: unless-stopped
    state: started
    volumes:
      - "{{ storage }}/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
